"""
Core Protocol definitions for Atlas (Worker Architecture).
"""
from typing import Any, Protocol, TypeVar

T = TypeVar("T")

class LifecycleProtocol(Protocol):
    @property
    def state(self) -> str: ...
    async def initialize(self) -> None: ...
    async def start(self) -> None: ...
    async def stop(self) -> None: ...
    async def dispose(self) -> None: ...


class WorkerManifest(Protocol):
    @property
    def id(self) -> str: ...
    @property
    def roles(self) -> list[str]: ...
    # Needs to expose required capabilities and exported capabilities


class WorkerProtocol(LifecycleProtocol, Protocol):
    @property
    def id(self) -> str: ...
    @property
    def name(self) -> str: ...
    @property
    def version(self) -> str: ...
    @property
    def manifest(self) -> WorkerManifest: ...
    
    # Handlers for Data Plane Session requests
    async def bind_capability(self, capability_name: str, requesting_worker_id: str) -> Any: ...


class ModelProtocol(Protocol):
    @property
    def name(self) -> str: ...
    @property
    def version(self) -> str: ...
    # Tool-independent metadata structure


class SessionProtocol(Protocol):
    @property
    def session_id(self) -> str: ...
    @property
    def source_worker_id(self) -> str: ...
    @property
    def target_worker_id(self) -> str: ...
    @property
    def capability_name(self) -> str: ...
    @property
    def binding(self) -> Any: ... # The actual RPC stub or object


class RegistryProtocol(Protocol):
    def register_worker(self, worker: WorkerProtocol) -> None: ...
    def register_model(self, model: ModelProtocol) -> None: ...
    def get_worker(self, worker_id: str) -> WorkerProtocol | None: ...
    def get_model(self, model_name: str) -> ModelProtocol | None: ...
    def get_workers_by_role(self, role: str) -> list[WorkerProtocol]: ...


class ConfigurationProtocol(Protocol):
    def get(self, key: str, default: Any = None) -> Any: ...
    def get_section(self, section: str) -> dict[str, Any]: ...
    def has(self, key: str) -> bool: ...
